# Generated by Django 5.1.5 on 2025-02-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado'), ('Em Atendimento', 'Em Atendimento')], default='Aberto', max_length=15),
        ),
    ]
